dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.7.0
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'
dotenv: .env
networks:
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  development:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
